[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "soda_citron"
version = "0.1.0"
description = "SODA-CitrON: Static Object Data Association by Clustering Multi-Modal Sensor Detections Online"
authors = [{ name="Jan Nausner", email="jan.nausner@ait.ac.at" }]
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}

# Runtime dependencies for installation via pip
dependencies = [
    "numpy",
    "scipy",
    "river==0.25",
    "python-ulid",
]

# Optional dependencies
[project.optional-dependencies]
example = [
    "jupyter",
    "shapely",
    "geopandas",
    "plotly",
]

# Links that show in package metadata
[project.urls]
Homepage = "https://git-service.ait.ac.at/cdt-rtsa/mufasa/data-association"
Repository = "https://git-service.ait.ac.at/cdt-rtsa/mufasa/data-association.git"
Issues = "https://git-service.ait.ac.at/cdt-rtsa/mufasa/data-association/-/issues"

# Package discovery using src/ layout
[tool.setuptools.packages.find]
where = ["src"]